[package]
name = "chip8-crab"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
derive_more = { version = "1.0.0", features = ["full"] }
regex = { version = "1.10.6" }
thiserror = "1.0.63"
ux = "0.1.6"
